// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ingest

import (
	"context"
	"github.com/bobcob7/lil-olt-metrics/internal/sessions"
	"github.com/bobcob7/lil-olt-metrics/internal/store"
	collogspb "go.opentelemetry.io/proto/otlp/collector/logs/v1"
	colmetricspb "go.opentelemetry.io/proto/otlp/collector/metrics/v1"
	"sync"
)

// Ensure, that metricsTranslatorMock does implement metricsTranslator.
// If this is not the case, regenerate this file with moq.
var _ metricsTranslator = &metricsTranslatorMock{}

// metricsTranslatorMock is a mock implementation of metricsTranslator.
//
//	func TestSomethingThatUsesmetricsTranslator(t *testing.T) {
//
//		// make and configure a mocked metricsTranslator
//		mockedmetricsTranslator := &metricsTranslatorMock{
//			TranslateFunc: func(req *colmetricspb.ExportMetricsServiceRequest, app store.Appender) (int, error) {
//				panic("mock out the Translate method")
//			},
//		}
//
//		// use mockedmetricsTranslator in code that requires metricsTranslator
//		// and then make assertions.
//
//	}
type metricsTranslatorMock struct {
	// TranslateFunc mocks the Translate method.
	TranslateFunc func(req *colmetricspb.ExportMetricsServiceRequest, app store.Appender) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Translate holds details about calls to the Translate method.
		Translate []struct {
			// Req is the req argument value.
			Req *colmetricspb.ExportMetricsServiceRequest
			// App is the app argument value.
			App store.Appender
		}
	}
	lockTranslate sync.RWMutex
}

// Translate calls TranslateFunc.
func (mock *metricsTranslatorMock) Translate(req *colmetricspb.ExportMetricsServiceRequest, app store.Appender) (int, error) {
	if mock.TranslateFunc == nil {
		panic("metricsTranslatorMock.TranslateFunc: method is nil but metricsTranslator.Translate was just called")
	}
	callInfo := struct {
		Req *colmetricspb.ExportMetricsServiceRequest
		App store.Appender
	}{
		Req: req,
		App: app,
	}
	mock.lockTranslate.Lock()
	mock.calls.Translate = append(mock.calls.Translate, callInfo)
	mock.lockTranslate.Unlock()
	return mock.TranslateFunc(req, app)
}

// TranslateCalls gets all the calls that were made to Translate.
// Check the length with:
//
//	len(mockedmetricsTranslator.TranslateCalls())
func (mock *metricsTranslatorMock) TranslateCalls() []struct {
	Req *colmetricspb.ExportMetricsServiceRequest
	App store.Appender
} {
	var calls []struct {
		Req *colmetricspb.ExportMetricsServiceRequest
		App store.Appender
	}
	mock.lockTranslate.RLock()
	calls = mock.calls.Translate
	mock.lockTranslate.RUnlock()
	return calls
}

// Ensure, that metricsStoreMock does implement metricsStore.
// If this is not the case, regenerate this file with moq.
var _ metricsStore = &metricsStoreMock{}

// metricsStoreMock is a mock implementation of metricsStore.
//
//	func TestSomethingThatUsesmetricsStore(t *testing.T) {
//
//		// make and configure a mocked metricsStore
//		mockedmetricsStore := &metricsStoreMock{
//			AppenderFunc: func(ctx context.Context) store.Appender {
//				panic("mock out the Appender method")
//			},
//		}
//
//		// use mockedmetricsStore in code that requires metricsStore
//		// and then make assertions.
//
//	}
type metricsStoreMock struct {
	// AppenderFunc mocks the Appender method.
	AppenderFunc func(ctx context.Context) store.Appender

	// calls tracks calls to the methods.
	calls struct {
		// Appender holds details about calls to the Appender method.
		Appender []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAppender sync.RWMutex
}

// Appender calls AppenderFunc.
func (mock *metricsStoreMock) Appender(ctx context.Context) store.Appender {
	if mock.AppenderFunc == nil {
		panic("metricsStoreMock.AppenderFunc: method is nil but metricsStore.Appender was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockAppender.Lock()
	mock.calls.Appender = append(mock.calls.Appender, callInfo)
	mock.lockAppender.Unlock()
	return mock.AppenderFunc(ctx)
}

// AppenderCalls gets all the calls that were made to Appender.
// Check the length with:
//
//	len(mockedmetricsStore.AppenderCalls())
func (mock *metricsStoreMock) AppenderCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockAppender.RLock()
	calls = mock.calls.Appender
	mock.lockAppender.RUnlock()
	return calls
}

// Ensure, that logsTranslatorMock does implement logsTranslator.
// If this is not the case, regenerate this file with moq.
var _ logsTranslator = &logsTranslatorMock{}

// logsTranslatorMock is a mock implementation of logsTranslator.
//
//	func TestSomethingThatUseslogsTranslator(t *testing.T) {
//
//		// make and configure a mocked logsTranslator
//		mockedlogsTranslator := &logsTranslatorMock{
//			TranslateFunc: func(req *collogspb.ExportLogsServiceRequest) ([]sessions.Event, error) {
//				panic("mock out the Translate method")
//			},
//		}
//
//		// use mockedlogsTranslator in code that requires logsTranslator
//		// and then make assertions.
//
//	}
type logsTranslatorMock struct {
	// TranslateFunc mocks the Translate method.
	TranslateFunc func(req *collogspb.ExportLogsServiceRequest) ([]sessions.Event, error)

	// calls tracks calls to the methods.
	calls struct {
		// Translate holds details about calls to the Translate method.
		Translate []struct {
			// Req is the req argument value.
			Req *collogspb.ExportLogsServiceRequest
		}
	}
	lockTranslate sync.RWMutex
}

// Translate calls TranslateFunc.
func (mock *logsTranslatorMock) Translate(req *collogspb.ExportLogsServiceRequest) ([]sessions.Event, error) {
	if mock.TranslateFunc == nil {
		panic("logsTranslatorMock.TranslateFunc: method is nil but logsTranslator.Translate was just called")
	}
	callInfo := struct {
		Req *collogspb.ExportLogsServiceRequest
	}{
		Req: req,
	}
	mock.lockTranslate.Lock()
	mock.calls.Translate = append(mock.calls.Translate, callInfo)
	mock.lockTranslate.Unlock()
	return mock.TranslateFunc(req)
}

// TranslateCalls gets all the calls that were made to Translate.
// Check the length with:
//
//	len(mockedlogsTranslator.TranslateCalls())
func (mock *logsTranslatorMock) TranslateCalls() []struct {
	Req *collogspb.ExportLogsServiceRequest
} {
	var calls []struct {
		Req *collogspb.ExportLogsServiceRequest
	}
	mock.lockTranslate.RLock()
	calls = mock.calls.Translate
	mock.lockTranslate.RUnlock()
	return calls
}

// Ensure, that sessionsStoreMock does implement sessionsStore.
// If this is not the case, regenerate this file with moq.
var _ sessionsStore = &sessionsStoreMock{}

// sessionsStoreMock is a mock implementation of sessionsStore.
//
//	func TestSomethingThatUsessessionsStore(t *testing.T) {
//
//		// make and configure a mocked sessionsStore
//		mockedsessionsStore := &sessionsStoreMock{
//			AppendEventFunc: func(ctx context.Context, evt sessions.Event) error {
//				panic("mock out the AppendEvent method")
//			},
//		}
//
//		// use mockedsessionsStore in code that requires sessionsStore
//		// and then make assertions.
//
//	}
type sessionsStoreMock struct {
	// AppendEventFunc mocks the AppendEvent method.
	AppendEventFunc func(ctx context.Context, evt sessions.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// AppendEvent holds details about calls to the AppendEvent method.
		AppendEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Evt is the evt argument value.
			Evt sessions.Event
		}
	}
	lockAppendEvent sync.RWMutex
}

// AppendEvent calls AppendEventFunc.
func (mock *sessionsStoreMock) AppendEvent(ctx context.Context, evt sessions.Event) error {
	if mock.AppendEventFunc == nil {
		panic("sessionsStoreMock.AppendEventFunc: method is nil but sessionsStore.AppendEvent was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Evt sessions.Event
	}{
		Ctx: ctx,
		Evt: evt,
	}
	mock.lockAppendEvent.Lock()
	mock.calls.AppendEvent = append(mock.calls.AppendEvent, callInfo)
	mock.lockAppendEvent.Unlock()
	return mock.AppendEventFunc(ctx, evt)
}

// AppendEventCalls gets all the calls that were made to AppendEvent.
// Check the length with:
//
//	len(mockedsessionsStore.AppendEventCalls())
func (mock *sessionsStoreMock) AppendEventCalls() []struct {
	Ctx context.Context
	Evt sessions.Event
} {
	var calls []struct {
		Ctx context.Context
		Evt sessions.Event
	}
	mock.lockAppendEvent.RLock()
	calls = mock.calls.AppendEvent
	mock.lockAppendEvent.RUnlock()
	return calls
}
