// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ingest

import (
	"context"
	"github.com/bobcob7/lil-olt-metrics/internal/store"
	colmetricspb "go.opentelemetry.io/proto/otlp/collector/metrics/v1"
	"sync"
)

// Ensure, that metricsTranslatorMock does implement metricsTranslator.
// If this is not the case, regenerate this file with moq.
var _ metricsTranslator = &metricsTranslatorMock{}

// metricsTranslatorMock is a mock implementation of metricsTranslator.
//
//	func TestSomethingThatUsesmetricsTranslator(t *testing.T) {
//
//		// make and configure a mocked metricsTranslator
//		mockedmetricsTranslator := &metricsTranslatorMock{
//			TranslateFunc: func(req *colmetricspb.ExportMetricsServiceRequest, app store.Appender) (int, error) {
//				panic("mock out the Translate method")
//			},
//		}
//
//		// use mockedmetricsTranslator in code that requires metricsTranslator
//		// and then make assertions.
//
//	}
type metricsTranslatorMock struct {
	// TranslateFunc mocks the Translate method.
	TranslateFunc func(req *colmetricspb.ExportMetricsServiceRequest, app store.Appender) (int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Translate holds details about calls to the Translate method.
		Translate []struct {
			// Req is the req argument value.
			Req *colmetricspb.ExportMetricsServiceRequest
			// App is the app argument value.
			App store.Appender
		}
	}
	lockTranslate sync.RWMutex
}

// Translate calls TranslateFunc.
func (mock *metricsTranslatorMock) Translate(req *colmetricspb.ExportMetricsServiceRequest, app store.Appender) (int, error) {
	if mock.TranslateFunc == nil {
		panic("metricsTranslatorMock.TranslateFunc: method is nil but metricsTranslator.Translate was just called")
	}
	callInfo := struct {
		Req *colmetricspb.ExportMetricsServiceRequest
		App store.Appender
	}{
		Req: req,
		App: app,
	}
	mock.lockTranslate.Lock()
	mock.calls.Translate = append(mock.calls.Translate, callInfo)
	mock.lockTranslate.Unlock()
	return mock.TranslateFunc(req, app)
}

// TranslateCalls gets all the calls that were made to Translate.
// Check the length with:
//
//	len(mockedmetricsTranslator.TranslateCalls())
func (mock *metricsTranslatorMock) TranslateCalls() []struct {
	Req *colmetricspb.ExportMetricsServiceRequest
	App store.Appender
} {
	var calls []struct {
		Req *colmetricspb.ExportMetricsServiceRequest
		App store.Appender
	}
	mock.lockTranslate.RLock()
	calls = mock.calls.Translate
	mock.lockTranslate.RUnlock()
	return calls
}

// Ensure, that metricsStoreMock does implement metricsStore.
// If this is not the case, regenerate this file with moq.
var _ metricsStore = &metricsStoreMock{}

// metricsStoreMock is a mock implementation of metricsStore.
//
//	func TestSomethingThatUsesmetricsStore(t *testing.T) {
//
//		// make and configure a mocked metricsStore
//		mockedmetricsStore := &metricsStoreMock{
//			AppenderFunc: func(ctx context.Context) store.Appender {
//				panic("mock out the Appender method")
//			},
//		}
//
//		// use mockedmetricsStore in code that requires metricsStore
//		// and then make assertions.
//
//	}
type metricsStoreMock struct {
	// AppenderFunc mocks the Appender method.
	AppenderFunc func(ctx context.Context) store.Appender

	// calls tracks calls to the methods.
	calls struct {
		// Appender holds details about calls to the Appender method.
		Appender []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAppender sync.RWMutex
}

// Appender calls AppenderFunc.
func (mock *metricsStoreMock) Appender(ctx context.Context) store.Appender {
	if mock.AppenderFunc == nil {
		panic("metricsStoreMock.AppenderFunc: method is nil but metricsStore.Appender was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockAppender.Lock()
	mock.calls.Appender = append(mock.calls.Appender, callInfo)
	mock.lockAppender.Unlock()
	return mock.AppenderFunc(ctx)
}

// AppenderCalls gets all the calls that were made to Appender.
// Check the length with:
//
//	len(mockedmetricsStore.AppenderCalls())
func (mock *metricsStoreMock) AppenderCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockAppender.RLock()
	calls = mock.calls.Appender
	mock.lockAppender.RUnlock()
	return calls
}
