// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package store

import (
	"context"
	"github.com/prometheus/prometheus/model/labels"
	"github.com/prometheus/prometheus/storage"
	"sync"
)

// Ensure, that StoreMock does implement Store.
// If this is not the case, regenerate this file with moq.
var _ Store = &StoreMock{}

// StoreMock is a mock implementation of Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked Store
//		mockedStore := &StoreMock{
//			AppenderFunc: func(ctx context.Context) Appender {
//				panic("mock out the Appender method")
//			},
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			LabelNamesFunc: func(ctx context.Context, mint int64, maxt int64, matchers ...*labels.Matcher) ([]string, error) {
//				panic("mock out the LabelNames method")
//			},
//			LabelValuesFunc: func(ctx context.Context, name string, mint int64, maxt int64, matchers ...*labels.Matcher) ([]string, error) {
//				panic("mock out the LabelValues method")
//			},
//			SelectFunc: func(ctx context.Context, sortSeries bool, mint int64, maxt int64, matchers ...*labels.Matcher) SeriesSet {
//				panic("mock out the Select method")
//			},
//		}
//
//		// use mockedStore in code that requires Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// AppenderFunc mocks the Appender method.
	AppenderFunc func(ctx context.Context) Appender

	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// LabelNamesFunc mocks the LabelNames method.
	LabelNamesFunc func(ctx context.Context, mint int64, maxt int64, matchers ...*labels.Matcher) ([]string, error)

	// LabelValuesFunc mocks the LabelValues method.
	LabelValuesFunc func(ctx context.Context, name string, mint int64, maxt int64, matchers ...*labels.Matcher) ([]string, error)

	// SelectFunc mocks the Select method.
	SelectFunc func(ctx context.Context, sortSeries bool, mint int64, maxt int64, matchers ...*labels.Matcher) SeriesSet

	// calls tracks calls to the methods.
	calls struct {
		// Appender holds details about calls to the Appender method.
		Appender []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// LabelNames holds details about calls to the LabelNames method.
		LabelNames []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Mint is the mint argument value.
			Mint int64
			// Maxt is the maxt argument value.
			Maxt int64
			// Matchers is the matchers argument value.
			Matchers []*labels.Matcher
		}
		// LabelValues holds details about calls to the LabelValues method.
		LabelValues []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
			// Mint is the mint argument value.
			Mint int64
			// Maxt is the maxt argument value.
			Maxt int64
			// Matchers is the matchers argument value.
			Matchers []*labels.Matcher
		}
		// Select holds details about calls to the Select method.
		Select []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SortSeries is the sortSeries argument value.
			SortSeries bool
			// Mint is the mint argument value.
			Mint int64
			// Maxt is the maxt argument value.
			Maxt int64
			// Matchers is the matchers argument value.
			Matchers []*labels.Matcher
		}
	}
	lockAppender    sync.RWMutex
	lockClose       sync.RWMutex
	lockLabelNames  sync.RWMutex
	lockLabelValues sync.RWMutex
	lockSelect      sync.RWMutex
}

// Appender calls AppenderFunc.
func (mock *StoreMock) Appender(ctx context.Context) Appender {
	if mock.AppenderFunc == nil {
		panic("StoreMock.AppenderFunc: method is nil but Store.Appender was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockAppender.Lock()
	mock.calls.Appender = append(mock.calls.Appender, callInfo)
	mock.lockAppender.Unlock()
	return mock.AppenderFunc(ctx)
}

// AppenderCalls gets all the calls that were made to Appender.
// Check the length with:
//
//	len(mockedStore.AppenderCalls())
func (mock *StoreMock) AppenderCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockAppender.RLock()
	calls = mock.calls.Appender
	mock.lockAppender.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *StoreMock) Close() error {
	if mock.CloseFunc == nil {
		panic("StoreMock.CloseFunc: method is nil but Store.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStore.CloseCalls())
func (mock *StoreMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// LabelNames calls LabelNamesFunc.
func (mock *StoreMock) LabelNames(ctx context.Context, mint int64, maxt int64, matchers ...*labels.Matcher) ([]string, error) {
	if mock.LabelNamesFunc == nil {
		panic("StoreMock.LabelNamesFunc: method is nil but Store.LabelNames was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Mint     int64
		Maxt     int64
		Matchers []*labels.Matcher
	}{
		Ctx:      ctx,
		Mint:     mint,
		Maxt:     maxt,
		Matchers: matchers,
	}
	mock.lockLabelNames.Lock()
	mock.calls.LabelNames = append(mock.calls.LabelNames, callInfo)
	mock.lockLabelNames.Unlock()
	return mock.LabelNamesFunc(ctx, mint, maxt, matchers...)
}

// LabelNamesCalls gets all the calls that were made to LabelNames.
// Check the length with:
//
//	len(mockedStore.LabelNamesCalls())
func (mock *StoreMock) LabelNamesCalls() []struct {
	Ctx      context.Context
	Mint     int64
	Maxt     int64
	Matchers []*labels.Matcher
} {
	var calls []struct {
		Ctx      context.Context
		Mint     int64
		Maxt     int64
		Matchers []*labels.Matcher
	}
	mock.lockLabelNames.RLock()
	calls = mock.calls.LabelNames
	mock.lockLabelNames.RUnlock()
	return calls
}

// LabelValues calls LabelValuesFunc.
func (mock *StoreMock) LabelValues(ctx context.Context, name string, mint int64, maxt int64, matchers ...*labels.Matcher) ([]string, error) {
	if mock.LabelValuesFunc == nil {
		panic("StoreMock.LabelValuesFunc: method is nil but Store.LabelValues was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Name     string
		Mint     int64
		Maxt     int64
		Matchers []*labels.Matcher
	}{
		Ctx:      ctx,
		Name:     name,
		Mint:     mint,
		Maxt:     maxt,
		Matchers: matchers,
	}
	mock.lockLabelValues.Lock()
	mock.calls.LabelValues = append(mock.calls.LabelValues, callInfo)
	mock.lockLabelValues.Unlock()
	return mock.LabelValuesFunc(ctx, name, mint, maxt, matchers...)
}

// LabelValuesCalls gets all the calls that were made to LabelValues.
// Check the length with:
//
//	len(mockedStore.LabelValuesCalls())
func (mock *StoreMock) LabelValuesCalls() []struct {
	Ctx      context.Context
	Name     string
	Mint     int64
	Maxt     int64
	Matchers []*labels.Matcher
} {
	var calls []struct {
		Ctx      context.Context
		Name     string
		Mint     int64
		Maxt     int64
		Matchers []*labels.Matcher
	}
	mock.lockLabelValues.RLock()
	calls = mock.calls.LabelValues
	mock.lockLabelValues.RUnlock()
	return calls
}

// Select calls SelectFunc.
func (mock *StoreMock) Select(ctx context.Context, sortSeries bool, mint int64, maxt int64, matchers ...*labels.Matcher) SeriesSet {
	if mock.SelectFunc == nil {
		panic("StoreMock.SelectFunc: method is nil but Store.Select was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		SortSeries bool
		Mint       int64
		Maxt       int64
		Matchers   []*labels.Matcher
	}{
		Ctx:        ctx,
		SortSeries: sortSeries,
		Mint:       mint,
		Maxt:       maxt,
		Matchers:   matchers,
	}
	mock.lockSelect.Lock()
	mock.calls.Select = append(mock.calls.Select, callInfo)
	mock.lockSelect.Unlock()
	return mock.SelectFunc(ctx, sortSeries, mint, maxt, matchers...)
}

// SelectCalls gets all the calls that were made to Select.
// Check the length with:
//
//	len(mockedStore.SelectCalls())
func (mock *StoreMock) SelectCalls() []struct {
	Ctx        context.Context
	SortSeries bool
	Mint       int64
	Maxt       int64
	Matchers   []*labels.Matcher
} {
	var calls []struct {
		Ctx        context.Context
		SortSeries bool
		Mint       int64
		Maxt       int64
		Matchers   []*labels.Matcher
	}
	mock.lockSelect.RLock()
	calls = mock.calls.Select
	mock.lockSelect.RUnlock()
	return calls
}

// Ensure, that AppenderMock does implement Appender.
// If this is not the case, regenerate this file with moq.
var _ Appender = &AppenderMock{}

// AppenderMock is a mock implementation of Appender.
//
//	func TestSomethingThatUsesAppender(t *testing.T) {
//
//		// make and configure a mocked Appender
//		mockedAppender := &AppenderMock{
//			AppendFunc: func(ref storage.SeriesRef, l labels.Labels, t int64, v float64) (storage.SeriesRef, error) {
//				panic("mock out the Append method")
//			},
//			CommitFunc: func() error {
//				panic("mock out the Commit method")
//			},
//			RollbackFunc: func() error {
//				panic("mock out the Rollback method")
//			},
//		}
//
//		// use mockedAppender in code that requires Appender
//		// and then make assertions.
//
//	}
type AppenderMock struct {
	// AppendFunc mocks the Append method.
	AppendFunc func(ref storage.SeriesRef, l labels.Labels, t int64, v float64) (storage.SeriesRef, error)

	// CommitFunc mocks the Commit method.
	CommitFunc func() error

	// RollbackFunc mocks the Rollback method.
	RollbackFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Append holds details about calls to the Append method.
		Append []struct {
			// Ref is the ref argument value.
			Ref storage.SeriesRef
			// L is the l argument value.
			L labels.Labels
			// T is the t argument value.
			T int64
			// V is the v argument value.
			V float64
		}
		// Commit holds details about calls to the Commit method.
		Commit []struct {
		}
		// Rollback holds details about calls to the Rollback method.
		Rollback []struct {
		}
	}
	lockAppend   sync.RWMutex
	lockCommit   sync.RWMutex
	lockRollback sync.RWMutex
}

// Append calls AppendFunc.
func (mock *AppenderMock) Append(ref storage.SeriesRef, l labels.Labels, t int64, v float64) (storage.SeriesRef, error) {
	if mock.AppendFunc == nil {
		panic("AppenderMock.AppendFunc: method is nil but Appender.Append was just called")
	}
	callInfo := struct {
		Ref storage.SeriesRef
		L   labels.Labels
		T   int64
		V   float64
	}{
		Ref: ref,
		L:   l,
		T:   t,
		V:   v,
	}
	mock.lockAppend.Lock()
	mock.calls.Append = append(mock.calls.Append, callInfo)
	mock.lockAppend.Unlock()
	return mock.AppendFunc(ref, l, t, v)
}

// AppendCalls gets all the calls that were made to Append.
// Check the length with:
//
//	len(mockedAppender.AppendCalls())
func (mock *AppenderMock) AppendCalls() []struct {
	Ref storage.SeriesRef
	L   labels.Labels
	T   int64
	V   float64
} {
	var calls []struct {
		Ref storage.SeriesRef
		L   labels.Labels
		T   int64
		V   float64
	}
	mock.lockAppend.RLock()
	calls = mock.calls.Append
	mock.lockAppend.RUnlock()
	return calls
}

// Commit calls CommitFunc.
func (mock *AppenderMock) Commit() error {
	if mock.CommitFunc == nil {
		panic("AppenderMock.CommitFunc: method is nil but Appender.Commit was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc()
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedAppender.CommitCalls())
func (mock *AppenderMock) CommitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// Rollback calls RollbackFunc.
func (mock *AppenderMock) Rollback() error {
	if mock.RollbackFunc == nil {
		panic("AppenderMock.RollbackFunc: method is nil but Appender.Rollback was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRollback.Lock()
	mock.calls.Rollback = append(mock.calls.Rollback, callInfo)
	mock.lockRollback.Unlock()
	return mock.RollbackFunc()
}

// RollbackCalls gets all the calls that were made to Rollback.
// Check the length with:
//
//	len(mockedAppender.RollbackCalls())
func (mock *AppenderMock) RollbackCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRollback.RLock()
	calls = mock.calls.Rollback
	mock.lockRollback.RUnlock()
	return calls
}
