// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package sessions

import (
	"context"
	"sync"
	"time"
)

// Ensure, that StoreMock does implement Store.
// If this is not the case, regenerate this file with moq.
var _ Store = &StoreMock{}

// StoreMock is a mock implementation of Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked Store
//		mockedStore := &StoreMock{
//			AppendEventFunc: func(ctx context.Context, evt Event) error {
//				panic("mock out the AppendEvent method")
//			},
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			GetEventsFunc: func(ctx context.Context, sessionID string, since time.Time, limit int) ([]Event, error) {
//				panic("mock out the GetEvents method")
//			},
//			GetSessionFunc: func(ctx context.Context, id string) (Session, error) {
//				panic("mock out the GetSession method")
//			},
//			ListSessionsFunc: func(ctx context.Context, since time.Time) ([]Session, error) {
//				panic("mock out the ListSessions method")
//			},
//		}
//
//		// use mockedStore in code that requires Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// AppendEventFunc mocks the AppendEvent method.
	AppendEventFunc func(ctx context.Context, evt Event) error

	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// GetEventsFunc mocks the GetEvents method.
	GetEventsFunc func(ctx context.Context, sessionID string, since time.Time, limit int) ([]Event, error)

	// GetSessionFunc mocks the GetSession method.
	GetSessionFunc func(ctx context.Context, id string) (Session, error)

	// ListSessionsFunc mocks the ListSessions method.
	ListSessionsFunc func(ctx context.Context, since time.Time) ([]Session, error)

	// calls tracks calls to the methods.
	calls struct {
		// AppendEvent holds details about calls to the AppendEvent method.
		AppendEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Evt is the evt argument value.
			Evt Event
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// GetEvents holds details about calls to the GetEvents method.
		GetEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SessionID is the sessionID argument value.
			SessionID string
			// Since is the since argument value.
			Since time.Time
			// Limit is the limit argument value.
			Limit int
		}
		// GetSession holds details about calls to the GetSession method.
		GetSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// ListSessions holds details about calls to the ListSessions method.
		ListSessions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Since is the since argument value.
			Since time.Time
		}
	}
	lockAppendEvent  sync.RWMutex
	lockClose        sync.RWMutex
	lockGetEvents    sync.RWMutex
	lockGetSession   sync.RWMutex
	lockListSessions sync.RWMutex
}

// AppendEvent calls AppendEventFunc.
func (mock *StoreMock) AppendEvent(ctx context.Context, evt Event) error {
	if mock.AppendEventFunc == nil {
		panic("StoreMock.AppendEventFunc: method is nil but Store.AppendEvent was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Evt Event
	}{
		Ctx: ctx,
		Evt: evt,
	}
	mock.lockAppendEvent.Lock()
	mock.calls.AppendEvent = append(mock.calls.AppendEvent, callInfo)
	mock.lockAppendEvent.Unlock()
	return mock.AppendEventFunc(ctx, evt)
}

// AppendEventCalls gets all the calls that were made to AppendEvent.
// Check the length with:
//
//	len(mockedStore.AppendEventCalls())
func (mock *StoreMock) AppendEventCalls() []struct {
	Ctx context.Context
	Evt Event
} {
	var calls []struct {
		Ctx context.Context
		Evt Event
	}
	mock.lockAppendEvent.RLock()
	calls = mock.calls.AppendEvent
	mock.lockAppendEvent.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *StoreMock) Close() error {
	if mock.CloseFunc == nil {
		panic("StoreMock.CloseFunc: method is nil but Store.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStore.CloseCalls())
func (mock *StoreMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// GetEvents calls GetEventsFunc.
func (mock *StoreMock) GetEvents(ctx context.Context, sessionID string, since time.Time, limit int) ([]Event, error) {
	if mock.GetEventsFunc == nil {
		panic("StoreMock.GetEventsFunc: method is nil but Store.GetEvents was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		SessionID string
		Since     time.Time
		Limit     int
	}{
		Ctx:       ctx,
		SessionID: sessionID,
		Since:     since,
		Limit:     limit,
	}
	mock.lockGetEvents.Lock()
	mock.calls.GetEvents = append(mock.calls.GetEvents, callInfo)
	mock.lockGetEvents.Unlock()
	return mock.GetEventsFunc(ctx, sessionID, since, limit)
}

// GetEventsCalls gets all the calls that were made to GetEvents.
// Check the length with:
//
//	len(mockedStore.GetEventsCalls())
func (mock *StoreMock) GetEventsCalls() []struct {
	Ctx       context.Context
	SessionID string
	Since     time.Time
	Limit     int
} {
	var calls []struct {
		Ctx       context.Context
		SessionID string
		Since     time.Time
		Limit     int
	}
	mock.lockGetEvents.RLock()
	calls = mock.calls.GetEvents
	mock.lockGetEvents.RUnlock()
	return calls
}

// GetSession calls GetSessionFunc.
func (mock *StoreMock) GetSession(ctx context.Context, id string) (Session, error) {
	if mock.GetSessionFunc == nil {
		panic("StoreMock.GetSessionFunc: method is nil but Store.GetSession was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetSession.Lock()
	mock.calls.GetSession = append(mock.calls.GetSession, callInfo)
	mock.lockGetSession.Unlock()
	return mock.GetSessionFunc(ctx, id)
}

// GetSessionCalls gets all the calls that were made to GetSession.
// Check the length with:
//
//	len(mockedStore.GetSessionCalls())
func (mock *StoreMock) GetSessionCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetSession.RLock()
	calls = mock.calls.GetSession
	mock.lockGetSession.RUnlock()
	return calls
}

// ListSessions calls ListSessionsFunc.
func (mock *StoreMock) ListSessions(ctx context.Context, since time.Time) ([]Session, error) {
	if mock.ListSessionsFunc == nil {
		panic("StoreMock.ListSessionsFunc: method is nil but Store.ListSessions was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Since time.Time
	}{
		Ctx:   ctx,
		Since: since,
	}
	mock.lockListSessions.Lock()
	mock.calls.ListSessions = append(mock.calls.ListSessions, callInfo)
	mock.lockListSessions.Unlock()
	return mock.ListSessionsFunc(ctx, since)
}

// ListSessionsCalls gets all the calls that were made to ListSessions.
// Check the length with:
//
//	len(mockedStore.ListSessionsCalls())
func (mock *StoreMock) ListSessionsCalls() []struct {
	Ctx   context.Context
	Since time.Time
} {
	var calls []struct {
		Ctx   context.Context
		Since time.Time
	}
	mock.lockListSessions.RLock()
	calls = mock.calls.ListSessions
	mock.lockListSessions.RUnlock()
	return calls
}
